apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - consumer-dlq.deployment.yaml
  - listener-live.deployment.yaml
  - parser-add-by-rss-ondemand.deployment.yaml
  - parser-add-by-rss-ondemand-background.deployment.yaml
  - parser-live.deployment.yaml
  - parser-normal.deployment.yaml
  - parser-ondemand.deployment.yaml
