apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-archive-all
spec:
  schedule: "0 6,18 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker
              image: ghcr.io/podverse/podverse/workers
              command: ["npm", "run", "archive_all"]
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              envFrom:
                - configMapRef:
                    name: podverse-workers-config
                - secretRef:
                    name: podverse-db-opaque
                - secretRef:
                    name: podverse-mq-opaque
                - secretRef:
                    name: podverse-api.podcastindex.org-opaque
              volumeMounts:
                - name: logs-volume
                  mountPath: /logs
                - name: logs-volume
                  mountPath: /opt/logs
          volumes:
            - name: logs-volume
              emptyDir: {}
          restartPolicy: OnFailure
