#!/usr/bin/env bash
# Combine all migrations into init_database.sql files
#
# Usage: ./scripts/database/combine-migrations.sh
# Requires Bash 4+ (use from repo dev shell or: ./scripts/nix/with-env ./scripts/database/combine-migrations.sh)
#
# This script combines migration files for both main and management databases
# into their respective combined/init_*.sql files.

set -e
shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

append_indented_file() {
	local source_file="$1"
	local indent="$2"
	local target_file="$3"

	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ -z "${line//[[:space:]]/}" ]]; then
			printf '\n' >>"$target_file"
			continue
		fi
		printf '%s%s\n' "$indent" "$line" >>"$target_file"
	done <"$source_file"
}

ensure_parent_dir() {
	local target_path="$1"
	local target_dir

	target_dir="$(dirname "$target_path")"
	mkdir -p "$target_dir"
}

copy_to_kustomize_sources() {
	# Create a symlink under infra/k8s/base/db/sources pointing to the canonical
	# file. Using symlinks avoids duplicating large SQL files while keeping the
	# kustomize reference inside the kustomize root. If a previous file/link
	# exists, remove it first.
	local src="$1"
	local dest="$2"
	local dest_dir

	dest_dir="$(dirname "$dest")"
	mkdir -p "$dest_dir"
	if [ -e "$dest" ] || [ -L "$dest" ]; then
		rm -f "$dest"
	fi
	# Try to create a hard link inside the kustomize root so kustomize sees the
	# file as "in or below" the kustomize dir. Hard links avoid duplicating the
	# content while keeping the file path inside the root. If hard link fails
	# (different filesystem), fall back to copying the file.
	if ! ln "$src" "$dest" 2>/dev/null; then
		cp "$src" "$dest"
	fi
}

# Main database
MAIN_MIGRATIONS="$REPO_ROOT/infra/database/migrations"
MAIN_COMBINED="$REPO_ROOT/infra/database/combined/init_database.sql"
MAIN_INIT_SCRIPTS="$REPO_ROOT/infra/database/init-scripts/01-create-users.sh"
MAIN_CONFIGMAP="$REPO_ROOT/infra/k8s/base/db/init-scripts.configmap.yaml"

echo "Combining main database migrations..."
ensure_parent_dir "$MAIN_COMBINED"
echo "-- Combined migrations generated $(date)" >"$MAIN_COMBINED"
echo "-- DO NOT EDIT - regenerate with scripts/database/combine-migrations.sh" >>"$MAIN_COMBINED"
echo "" >>"$MAIN_COMBINED"

main_migrations=("$MAIN_MIGRATIONS"/*.sql)
if ((${#main_migrations[@]} > 0)); then
	mapfile -t main_migrations_sorted < <(printf '%s\n' "${main_migrations[@]}" | sort)
	for migration in "${main_migrations_sorted[@]}"; do
		{
			echo "-- Including: $(basename "$migration")"
			cat "$migration"
			echo ""
			echo ""
		} >>"$MAIN_COMBINED"
	done
fi

echo "✓ Main database combined: $MAIN_COMBINED"

echo "NOTE: K8s ConfigMap files are now generated by kustomize via infra/k8s/base/db/kustomization.yaml"
echo "✓ Combined SQL written: $MAIN_COMBINED"
echo "Copying main files into kustomize sources..."
copy_to_kustomize_sources "$MAIN_COMBINED" "$REPO_ROOT/infra/k8s/base/db/sources/main_00_init_database.sql"
copy_to_kustomize_sources "$MAIN_INIT_SCRIPTS" "$REPO_ROOT/infra/k8s/base/db/sources/main_01-create-users.sh"

# Management database
MGMT_MIGRATIONS="$REPO_ROOT/infra/database/management/migrations"
MGMT_COMBINED="$REPO_ROOT/infra/database/management/combined/init_management_database.sql"
MGMT_INIT_SCRIPTS="$REPO_ROOT/infra/database/management/init-scripts/01-create-users.sh"
MGMT_CONFIGMAP="$REPO_ROOT/infra/k8s/base/db/management-init-scripts.configmap.yaml"

echo "Combining management database migrations..."
ensure_parent_dir "$MGMT_COMBINED"
echo "-- Combined migrations generated $(date)" >"$MGMT_COMBINED"
echo "-- DO NOT EDIT - regenerate with scripts/database/combine-migrations.sh" >>"$MGMT_COMBINED"
echo "" >>"$MGMT_COMBINED"

mgmt_migrations=("$MGMT_MIGRATIONS"/*.sql)
if ((${#mgmt_migrations[@]} > 0)); then
	mapfile -t mgmt_migrations_sorted < <(printf '%s\n' "${mgmt_migrations[@]}" | sort)
	for migration in "${mgmt_migrations_sorted[@]}"; do
		{
			echo "-- Including: $(basename "$migration")"
			cat "$migration"
			echo ""
			echo ""
		} >>"$MGMT_COMBINED"
	done
fi

echo "✓ Management database combined: $MGMT_COMBINED"

echo "NOTE: K8s ConfigMap files are now generated by kustomize via infra/k8s/base/db/kustomization.yaml"
echo "✓ Management combined SQL written: $MGMT_COMBINED"
echo "Copying management files into kustomize sources..."
copy_to_kustomize_sources "$MGMT_COMBINED" "$REPO_ROOT/infra/k8s/base/db/sources/mgmt_00_init_management_database.sql"
copy_to_kustomize_sources "$MGMT_INIT_SCRIPTS" "$REPO_ROOT/infra/k8s/base/db/sources/mgmt_01-create-users.sh"
echo ""
echo "Done! Both databases combined successfully."
