# Version: 1
# Filename: kustomization.yaml
# Description: Bundles the Web frontend resources and centralizes the web image tag.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/podverse/podverse/infra/k8s/base/web?ref=feature/alpha

namespace: podverse-alpha

labels:
  - pairs:
      app: podverse-web
      environment: alpha
    # This ensures the labels are also applied to the selectors,
    # so the Service correctly finds the Pods.
    includeSelectors: true

images:
  - name: ghcr.io/podverse/podverse-web-deploy
    newTag: "5.1.28-alpha.0"

patches:
  - path: deployment-link-patch.yaml
